TRAIN:
  CHECKPOINTS_KEPT : 10
  CHECKPOINTS_EPOCHS : 5
  MAX_EPOCHS : 300
  BATCH_SIZE : 128
  TRAINABLE_SCOPE : 'base,extras,norm,loc,conf'
  RESUME_SCOPE : ''

  OPTIMIZER:
    OPTIMIZER : sgd
    LEARNING_RATE : 0.001
    MOMENTUM : 0.9
    MOMENTUM_2 : 0.99
    EPS : 1e-8
    WEIGHT_DECAY : 0.0001

  LR_SCHEDULER:
    SCHEDULER : step
    STEPS : [1]
    GAMMA : 0.98
    WARM_UP_EPOCHS : 0
    MAX_EPOCHS : 300
    
DATASET:
  DATASET : 'voc'
  DATASET_DIR : "/"
  TRAIN_SETS : []
  TEST_SETS : []
  PROB : 0.6
  IMAGE_SIZE : [300, 300]
  PIXEL_MEANS : (103.94, 116.78, 123.68)
  TRAIN_BATCH_SIZE : 128
  TEST_BATCH_SIZE : 128
  NUM_WORKERS : 8